[[models]]
# モデル名
name = "Rice"
# ビルボーディング表示設定
billboarding = false
# 非モーション再生時の呼吸動作設定
enablebreathing = true
# AR 空間上のモデルの拡大率
scale = 1
# AR 空間上のモデルの表示位置
[models.position]
x = 0 # 左右位置
y = 0 # 上下位置
z = 0 # 前後位置
# AR 空間上のモデルの表示角度調整
[models.rotation]
x = 0 # X軸回転
y = 0 # Y軸回転
z = 0 # Z軸回転
# AR 空間上のモデルのオフセット
[models.canvasOffset]
x = 0
y = 0
# モデルの当たり判定とモーショングループの紐付け
[models.hitInfo]
# 当たり判定ID = "モーショングループ名"
# 全体の設定
[global]
# マーカーARモードとツーショットARモードの切替の許可設定
allowModeSwitch = true
# 起動時のモード設定
startupMode = 0
